langflow:
  enabled: true
postgresql:
  enabled: true
qdrant:
  enabled: true
open-webui:
  enabled: true
pipelines:
  enabled: true

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true

service:
  type: ClusterIP
  port: 7860

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: '{{ .Values.ingress.host | default "chart-example.local" }}'
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []