openWebUI:
  hostname: open-webui
  containerName: open-webui
  image:
    repository: mathieuawels/openwebui-awels
    tag: latest
    pullPolicy: IfNotPresent  

resources:
  limits:
    memory: 2Gi    # Increased from 1Gi
    cpu: 1
  requests:
    memory: 512Mi  # Reduced request to allow for startup
    cpu: 500m

initContainers:
  enabled: true
  openwebui:
    image: alpine:latest
    env: |
      AWELS_HOST=127.0.0.1
      WEBUI_SECRET_KEY=changeme
      ENABLE_SIGNUP=true
      ENABLE_LOGIN_FORM=true
    script: |
      #!/bin/sh
      echo "Initialisation d'Open WebUI..." 
      echo "Lancement du script d'initialisation terminé"


restartPolicy: "unless-stopped"

service:
  type: ClusterIP
  port: 3000

ports:
  port: 3000
  internalPort: 8080

secrets:
  qdrant_api_key: "your-qdrant-api-key"
  websocket_redis_url: "redis://redis:6379/1"
  webui_secret_key: "your-secret-key"
  langflowdatabaseurl: >
    postgresql://{{ .Values.postgresql.auth.username }}:pass@{{ include "postgresql.fullname" . }}:5432/{{ include "langflow.fullname" . }}

postgresql:
  auth:
    username: "awels"
    database: "awels_db"
env: 
  awelsHost: "127.0.0.1"
  enableSignup: "True"
  enableLoginForm: "True"
  enablePersistentConfig: "True"
  databasePoolRecycle: 3600
  enableWebsocketSupport: "True"
  websocketManager: "redis"
  vectorDb: "qdrant"
  qdrantUri: "http://qdrant:6333"
  qdrantPreferGrpc: "False"
  qdrantGrpcPort: 6334
  name: USER_AGENT
  value: "OpenWebUI/1.0"

persistence:
  enabled: true
  size: "10Gi"
  accessMode: ReadWriteOnce
  storageClass: "" 
  existingClaim: "" 

replicaCount: 1

serviceAccount:
 
  create: false
  annotations: {}
  name: ""
  automount: true

healthcheck:
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  startupProbe:
    failureThreshold: 30    # Allow up to 5 minutes for startup (30 * 10s)
    periodSeconds: 10
    timeoutSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80


strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0


podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: false
  runAsRoot: true

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []




