image:
  repository: ghcr.io/open-webui/pipelines
  tag: main
  pullPolicy: IfNotPresent

# Default values for the chart
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 9099

resources:
  limits:
    cpu: 1.0
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 512Mi

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

config:
  port: 9099
  logLevel: info


env:
  - name: PORT
    value: "9099"   # valeur littérale

  - name: PIPELINES_API_KEY
    valueFrom:
      secretKeyRef:   
        name: pipelines_secrets 
        key: api-key

  - name: LOG_LEVEL
    value: "info"


# Healthcheck configuration
healthcheck:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

serviceAccount:
  create: true
  name: ""  # vide = Helm générera le nom automatiquement
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: pipelines.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80  #

persistence:
  # Activer ou désactiver la persistance
  enabled: true
  # Annotations à ajouter au PVC (optionnel)
  annotations: {}
  # Modes d'accès au volume
  accessModes:
    - ReadWriteOnce
  # Classe de stockage à utiliser
  storageClassName: "standard"
  # Taille du volume persistant
  size: "10Gi"


