apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipelines.fullname" . }}-secrets
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: "0p3n-w3bu!"
