apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-webui.fullname" . }}-secrets
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | upper }}: {{ tpl $value $ | quote }}
  {{- end }}

