apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langflow.fullname" . }}-secrets
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | upper }}: {{ $value | b64enc | quote }}
  {{- end }}